server:
  port: 8081

spring:
  application:
    name: "accounts"
  profiles:
    active: "dev"
  datasource:
    url: jdbc:h2:mem:accountsdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      # create db and tables automatically when server starts
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
  config:
    import: "optional:configserver:http://localhost:8888"

